# Plugin documentation can be found at https://rpp.oglass.dev/docs/plugin

[plugin]
id = "{{ id }}"
# The version must be formatted as a SemVer
version = "{{ version }}"
description = "{{ description }}"

# To use external libraries (add to Lua's package.path), use include
# include = ["../../lib/"]
#
# To use external c libraries (add to Lua's package.cpath), use include_c
# include_c = ["/usr/lib"]
