# Config documentation can be found at https://rpp.oglass.dev/docs/config
[rpp]
root_dir = "{{ root }}"
plugins = [
    # Example: using a local plugin
    # "local:example"
]

[server]
host = "127.0.0.1"
port = 6741
default_pack = "idk"
