[package]
name = "rpp-cli"
description = "The CLI for rpp"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "rpp"
path = "src/main.rs"

[dependencies]
rpp = { workspace = true, features = ["js", "wasm", "tracing"] }
rpp-archive.workspace = true
rpp-fetch.workspace = true
rpp-js.workspace = true
rpp-squash.workspace = true
rpp-wasm.workspace = true

anyhow.workspace = true
clap = { version = "4.5", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
semver.workspace = true
sha2.workspace = true
sha1.workspace = true

tracing.workspace = true
wit-component.workspace = true
wit-parser.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

cliclack = "0.5.6"

tokio = { workspace = true, features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "signal",
  "time",
  "fs",
  "net",
] }
tokio-stream = { version = "0.1", features = ["sync"] }
axum = "0.7"
tower-http = { version = "0.6", features = ["fs"] }
notify-debouncer-full = "0.3"
open = "5"
tempfile.workspace = true

[dev-dependencies]
flate2.workspace = true
tar.workspace = true
png.workspace = true
zip.workspace = true
wit-component = { workspace = true, features = ["dummy-module"] }

[lints]
workspace = true
