//! TypeScript declarations for WASM components, following the jco type mapping.

mod names;

use std::collections::{HashMap, HashSet, VecDeque};

use anyhow::{bail, Context, Result};
use wit_parser::{
    Function, FunctionKind, Resolve, Result_, Type, TypeDefKind, TypeId, TypeOwner, WorldId,
    WorldItem, WorldKey,
};

use self::names::{identifier, pascal_case, property_key, quote_key, type_name};

/// Declarations for the component binary `bytes`, exposed as `name` in `ComponentMap`.
pub fn from_wasm(name: &str, bytes: &[u8]) -> Result<String> {
    match wit_component::decode(bytes).context("decoding the component")? {
        wit_component::DecodedWasm::Component(resolve, world) => {
            Ok(generate(name, &resolve, world))
        }
        wit_component::DecodedWasm::WitPackage(..) => {
            bail!("expected a component, found a WIT package")
        }
    }
}

/// Declarations for the exports of `world`, exposed as `name` in `ComponentMap`.
pub fn generate(name: &str, resolve: &Resolve, world: WorldId) -> String {
    let mut gen = Generator::new(resolve);
    let exports_name = type_name(name);
    gen.used.insert(exports_name.clone());

    for (id, def) in resolve.types.iter() {
        let declared = match def.owner {
            TypeOwner::World(id) => id == world,
            TypeOwner::Interface(id) => resolve.worlds[world].exports.values().any(
                |item| matches!(item, WorldItem::Interface { id: export, .. } if *export == id),
            ),
            TypeOwner::None => false,
        };
        if declared && def.name.is_some() {
            gen.type_ref(&Type::Id(id));
        }
    }

    let exports = gen.exports(world, 1);
    let mut out = String::from("// Generated by `rpp codegen`; do not edit.\n");
    while let Some(id) = gen.queue.pop_front() {
        let definition = gen.define(id);
        out.push_str(&definition);
    }
    out.push_str(&format!("export interface {exports_name} {exports}\n"));
    out.push_str(&format!(
        "declare module \"rpp\" {{\n  interface ComponentMap {{\n    {}: {exports_name};\n  }}\n}}\n",
        quote_key(name)
    ));
    out
}

struct Generator<'a> {
    resolve: &'a Resolve,
    names: HashMap<TypeId, String>,
    used: HashSet<String>,
    queue: VecDeque<TypeId>,
}

impl<'a> Generator<'a> {
    fn new(resolve: &'a Resolve) -> Self {
        Self {
            resolve,
            names: HashMap::new(),
            used: HashSet::new(),
            queue: VecDeque::new(),
        }
    }

    fn exports(&mut self, world: WorldId, depth: usize) -> String {
        let resolve = self.resolve;
        let mut members = Vec::new();
        for (key, item) in &resolve.worlds[world].exports {
            match item {
                WorldItem::Function(func) => {
                    if let Some(member) = self.function(func) {
                        members.push(member);
                    }
                }
                WorldItem::Interface { id, .. } => {
                    let interface = &resolve.interfaces[*id];
                    let name = match key {
                        WorldKey::Name(name) => name.clone(),
                        WorldKey::Interface(_) => interface.name.clone().unwrap_or_default(),
                    };
                    let functions: Vec<String> = interface
                        .functions
                        .values()
                        .filter_map(|func| self.function(func))
                        .collect();
                    members.push(format!(
                        "{}: {};",
                        property_key(&name),
                        object(&functions, depth + 1)
                    ));
                }
                WorldItem::Type { .. } => {}
            }
        }
        object(&members, depth)
    }

    /// `name: (params) => result;`, or `None` for resource methods.
    fn function(&mut self, func: &Function) -> Option<String> {
        if !matches!(func.kind, FunctionKind::Freestanding) {
            return None;
        }
        let params: Vec<String> = func
            .params
            .iter()
            .map(|param| format!("{}: {}", identifier(&param.name), self.type_ref(&param.ty)))
            .collect();
        let result = match &func.result {
            None => "void".to_string(),
            Some(ty) => match self.ok_type(ty) {
                Some(Some(ok)) => self.type_ref(&ok),
                Some(None) => "void".to_string(),
                None => self.type_ref(ty),
            },
        };
        Some(format!(
            "{}: ({}) => {};",
            property_key(&func.name),
            params.join(", "),
            result
        ))
    }

    /// The ok type of a `result` type, or `None` when `ty` is not a result.
    fn ok_type(&self, ty: &Type) -> Option<Option<Type>> {
        match self.resolved_kind(ty) {
            Some(TypeDefKind::Result(Result_ { ok, .. })) => Some(*ok),
            _ => None,
        }
    }

    /// The kind of `ty` after following aliases.
    fn resolved_kind(&self, ty: &Type) -> Option<&'a TypeDefKind> {
        let mut ty = *ty;
        loop {
            let Type::Id(id) = ty else { return None };
            match &self.resolve.types[id].kind {
                TypeDefKind::Type(inner) => ty = *inner,
                kind => return Some(kind),
            }
        }
    }

    fn type_ref(&mut self, ty: &Type) -> String {
        match ty {
            Type::Bool => "boolean".into(),
            Type::U8 | Type::U16 | Type::U32 | Type::S8 | Type::S16 | Type::S32 => "number".into(),
            Type::F32 | Type::F64 => "number".into(),
            Type::U64 | Type::S64 => "bigint".into(),
            Type::Char | Type::String => "string".into(),
            Type::ErrorContext => "unknown".into(),
            Type::Id(id) => {
                let def = &self.resolve.types[*id];
                self.body(def.name.as_ref().map(|_| *id), &def.kind)
            }
        }
    }

    fn name_of(&mut self, id: TypeId) -> String {
        if let Some(name) = self.names.get(&id) {
            return name.clone();
        }
        let def = &self.resolve.types[id];
        let base = type_name(def.name.as_deref().unwrap_or("type"));
        let mut name = base.clone();
        if self.used.contains(&name) {
            if let TypeOwner::Interface(interface) = def.owner {
                if let Some(owner) = &self.resolve.interfaces[interface].name {
                    name = type_name(&format!("{}{base}", pascal_case(owner)));
                }
            }
        }
        let mut suffix = 2;
        let unique = name.clone();
        while self.used.contains(&name) {
            name = format!("{unique}{suffix}");
            suffix += 1;
        }
        self.used.insert(name.clone());
        self.names.insert(id, name.clone());
        self.queue.push_back(id);
        name
    }

    fn define(&mut self, id: TypeId) -> String {
        let name = self.names[&id].clone();
        let kind = &self.resolve.types[id].kind;
        if let TypeDefKind::Record(record) = kind {
            let fields = self.record_fields(record);
            return format!("export interface {name} {}\n", object(&fields, 1));
        }
        let body = match kind {
            TypeDefKind::Type(inner) => self.type_ref(inner),
            kind => self.body(None, kind),
        };
        format!("export type {name} = {body};\n")
    }

    fn record_fields(&mut self, record: &wit_parser::Record) -> Vec<String> {
        record
            .fields
            .iter()
            .map(|field| {
                format!(
                    "{}: {};",
                    property_key(&field.name),
                    self.type_ref(&field.ty)
                )
            })
            .collect()
    }

    /// Renders `kind`, referencing it by name when `named` is set and it has a TypeScript form.
    fn body(&mut self, named: Option<TypeId>, kind: &TypeDefKind) -> String {
        match (kind, named) {
            (
                TypeDefKind::Resource
                | TypeDefKind::Handle(_)
                | TypeDefKind::Future(_)
                | TypeDefKind::Stream(_)
                | TypeDefKind::Unknown,
                _,
            ) => "unknown".into(),
            (_, Some(id)) => self.name_of(id),
            (TypeDefKind::Record(record), None) => {
                let fields = self.record_fields(record);
                inline_object(&fields)
            }
            (TypeDefKind::Flags(flags), None) => {
                let fields: Vec<String> = flags
                    .flags
                    .iter()
                    .map(|flag| format!("{}?: boolean;", property_key(&flag.name)))
                    .collect();
                inline_object(&fields)
            }
            (TypeDefKind::Tuple(tuple), None) => {
                let items: Vec<String> = tuple.types.iter().map(|ty| self.type_ref(ty)).collect();
                format!("[{}]", items.join(", "))
            }
            (TypeDefKind::Variant(variant), None) => self.variant_body(variant),
            (TypeDefKind::Enum(en), None) => union(
                en.cases
                    .iter()
                    .map(|case| format!("{:?}", case.name))
                    .collect(),
            ),
            (TypeDefKind::Option(inner), None) => self.option_body(inner),
            (TypeDefKind::Result(result), None) => {
                let ok = result.ok.as_ref().map(|ty| self.type_ref(ty));
                let err = result.err.as_ref().map(|ty| self.type_ref(ty));
                union(vec![
                    tagged("ok", ok.as_deref()),
                    tagged("err", err.as_deref()),
                ])
            }
            (TypeDefKind::List(Type::U8), None) => "Uint8Array".into(),
            (TypeDefKind::List(inner) | TypeDefKind::FixedLengthList(inner, _), None) => {
                self.list_body(inner)
            }
            (TypeDefKind::Map(key, value), None) => {
                format!("Map<{}, {}>", self.type_ref(key), self.type_ref(value))
            }
            (TypeDefKind::Type(inner), None) => self.type_ref(inner),
        }
    }

    fn variant_body(&mut self, variant: &wit_parser::Variant) -> String {
        let cases: Vec<String> = variant
            .cases
            .iter()
            .map(|case| {
                let val = case.ty.as_ref().map(|ty| self.type_ref(ty));
                tagged(&case.name, val.as_deref())
            })
            .collect();
        union(cases)
    }

    fn option_body(&mut self, inner: &Type) -> String {
        let val = self.type_ref(inner);
        if matches!(self.resolved_kind(inner), Some(TypeDefKind::Option(_))) {
            union(vec![tagged("some", Some(&val)), tagged("none", None)])
        } else {
            format!("{val} | undefined")
        }
    }

    fn list_body(&mut self, inner: &Type) -> String {
        let item = self.type_ref(inner);
        if has_top_level_union(&item) {
            format!("({item})[]")
        } else {
            format!("{item}[]")
        }
    }
}

fn tagged(tag: &str, val: Option<&str>) -> String {
    match val {
        Some(val) => format!("{{ tag: {tag:?}; val: {val} }}"),
        None => format!("{{ tag: {tag:?} }}"),
    }
}

fn union(cases: Vec<String>) -> String {
    if cases.is_empty() {
        "never".into()
    } else {
        cases.join(" | ")
    }
}

fn inline_object(members: &[String]) -> String {
    if members.is_empty() {
        "{}".into()
    } else {
        format!("{{ {} }}", members.join(" ").trim_end_matches(';'))
    }
}

/// A multi-line object type with each member on its own line, indented by `depth`.
fn object(members: &[String], depth: usize) -> String {
    if members.is_empty() {
        return "{}".into();
    }
    let indent = "  ".repeat(depth);
    let mut out = String::from("{\n");
    for member in members {
        out.push_str(&format!("{indent}{member}\n"));
    }
    out.push_str(&format!("{}}}", "  ".repeat(depth - 1)));
    out
}

/// Whether `ty` contains a `|` outside brackets and string literals.
fn has_top_level_union(ty: &str) -> bool {
    let (mut depth, mut quoted, mut escaped) = (0usize, false, false);
    for c in ty.chars() {
        match c {
            _ if escaped => escaped = false,
            '\\' if quoted => escaped = true,
            '"' => quoted = !quoted,
            _ if quoted => {}
            '{' | '[' | '(' | '<' => depth += 1,
            '}' | ']' | ')' | '>' => depth = depth.saturating_sub(1),
            '|' if depth == 0 => return true,
            _ => {}
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dts_named(name: &str, wit: &str) -> String {
        let mut resolve = Resolve::default();
        let package = resolve.push_str("test.wit", wit).unwrap();
        let world = resolve.select_world(&[package], None).unwrap();
        generate(name, &resolve, world)
    }

    fn dts(wit: &str) -> String {
        dts_named("compiler", wit)
    }

    #[test]
    fn dts_named_records_and_aliases() {
        let out = dts(r#"package t:c;
world w {
  record parse-error { line-number: u32, message: string }
  type errors = list<parse-error>;
  flags perms { can-read, can-write }
  enum level { low, high }
  variant shape { dot, circle(f64) }
  export check: func(e: parse-error, p: perms, l: level, s: shape) -> errors;
}"#);
        assert!(
            out.contains(
                "export interface ParseError {\n  lineNumber: number;\n  message: string;\n}"
            ),
            "{out}"
        );
        assert!(out.contains("export type Errors = ParseError[];"), "{out}");
        assert!(
            out.contains("export type Perms = { canRead?: boolean; canWrite?: boolean };"),
            "{out}"
        );
        assert!(
            out.contains("export type Level = \"low\" | \"high\";"),
            "{out}"
        );
        assert!(
            out.contains(
                "export type Shape = { tag: \"dot\" } | { tag: \"circle\"; val: number };"
            ),
            "{out}"
        );
        assert!(
            out.contains("check: (e: ParseError, p: Perms, l: Level, s: Shape) => Errors;"),
            "{out}"
        );
    }

    #[test]
    fn dts_bigint_uint8array_option_nesting() {
        let out = dts(r#"package t:c;
world w {
  export f: func(a: u64, b: s64, c: list<u8>, d: option<u32>, e: option<option<u32>>, t: tuple<char, u8>);
}"#);
        assert!(
            out.contains("a: bigint, b: bigint, c: Uint8Array, d: number | undefined,"),
            "{out}"
        );
        assert!(
            out.contains("e: { tag: \"some\"; val: number | undefined } | { tag: \"none\" }"),
            "{out}"
        );
        assert!(out.contains("t: [string, number]) => void;"), "{out}");
    }

    #[test]
    fn dts_result_function_returns_ok_type() {
        let out = dts(r#"package t:c;
world w {
  export compile: func() -> result<string, string>;
  export ping: func() -> result<_, u32>;
  export pair: func() -> list<result<u8, string>>;
}"#);
        assert!(out.contains("compile: () => string;"), "{out}");
        assert!(out.contains("ping: () => void;"), "{out}");
        assert!(
            out.contains(
                "pair: () => ({ tag: \"ok\"; val: number } | { tag: \"err\"; val: string })[];"
            ),
            "{out}"
        );
    }

    #[test]
    fn dts_component_map_augmentation() {
        let out = dts(r#"package t:c@1.0.0;
interface tools { frob: func(n: s64) -> s64; }
world w { export tools; export run: func(); }"#);
        assert!(out.contains("export interface Compiler {\n  run: () => void;\n  tools: {\n    frob: (n: bigint) => bigint;\n  };\n}"), "{out}");
        assert!(
            out.ends_with(
                "declare module \"rpp\" {\n  interface ComponentMap {\n    compiler: Compiler;\n  }\n}\n"
            ),
            "{out}"
        );
    }

    #[test]
    fn dts_component_map_key_is_the_exact_name() {
        let out = dts_named("my-calc", "package t:c;\nworld w { export run: func(); }");
        assert!(out.contains("\"my-calc\": MyCalc;"), "{out}");
        let out = dts_named("calc_2", "package t:c;\nworld w { export run: func(); }");
        assert!(out.contains("    calc_2: Calc2;"), "{out}");
    }

    #[test]
    fn dts_names_do_not_shadow_globals() {
        let out = dts_named(
            "array",
            r#"package t:c;
world w {
  record error { code: u32 }
  export f: func(items: list<u32>, e: error, o: list<option<u8>>) -> list<error>;
}"#,
        );
        assert!(out.contains("export interface Array_ {"), "{out}");
        assert!(out.contains("export interface Error_ {"), "{out}");
        assert!(
            out.contains("(items: number[], e: Error_, o: (number | undefined)[]) => Error_[];"),
            "{out}"
        );
        assert!(out.contains("array: Array_;"), "{out}");
    }
}
