//! `rpp component ...`: utilities for WASM component libraries.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::Subcommand;
use rpp_wasm::{Function, ValueType, WasmEngine};

/// Component subcommands.
#[derive(Debug, Subcommand)]
pub enum ComponentCommand {
    /// Generate a typed Lua wrapper for a component binary.
    Bindgen {
        /// Component binary to inspect.
        wasm: PathBuf,
        /// Component name from `[component.<name>]` in plugin.toml.
        #[arg(long)]
        name: String,
        /// Lua module path to write.
        #[arg(long)]
        out: PathBuf,
    },
}

/// Run a component subcommand.
pub fn run(dir: &Path, command: ComponentCommand) -> Result<()> {
    match command {
        ComponentCommand::Bindgen { wasm, name, out } => {
            bindgen(&dir.join(wasm), &name, &dir.join(out))
        }
    }
}

fn bindgen(wasm: &Path, name: &str, out: &Path) -> Result<()> {
    let engine = WasmEngine::new().context("initializing component engine")?;
    let component = engine
        .load(wasm)
        .with_context(|| format!("loading component {}", wasm.display()))?;
    let text = generate_lua(name, &component.schema().functions);
    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(out, text).with_context(|| format!("writing {}", out.display()))
}

fn generate_lua(name: &str, functions: &[Function]) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "-- Generated by rpp component bindgen; do not edit.\n\
         local rpp = require(\"rpp\")\n\
         local component = rpp.component.load({:?})\n\
         local M = {{}}\n",
        name
    )
    .unwrap();
    let bindings = function_bindings(functions);
    let component_type = pascal_case(name);

    for binding in &bindings {
        let prefix = format!("{component_type}{}", pascal_case(&binding.lua_name));
        let mut aliases = Vec::new();
        let mut used_aliases = BTreeSet::new();
        let param_types = binding
            .function
            .params
            .iter()
            .map(|(param, ty)| {
                annotated_type(
                    ty,
                    format!("{prefix}{}", pascal_case(param)),
                    &mut aliases,
                    &mut used_aliases,
                )
            })
            .collect::<Vec<_>>();
        let result_types = binding
            .function
            .results
            .iter()
            .enumerate()
            .map(|(index, ty)| {
                let suffix = if binding.function.results.len() == 1 {
                    "Result".to_string()
                } else {
                    format!("Result{}", index + 1)
                };
                annotated_type(
                    ty,
                    format!("{prefix}{suffix}"),
                    &mut aliases,
                    &mut used_aliases,
                )
            })
            .collect::<Vec<_>>();

        for (alias, definition) in aliases {
            writeln!(out, "---@alias {alias} {definition}").unwrap();
        }
        if !used_aliases.is_empty() {
            out.push('\n');
        }
        for ((param, _), ty) in binding.function.params.iter().zip(&param_types) {
            writeln!(out, "---@param {} {ty}", param_name(param)).unwrap();
        }
        if !result_types.is_empty() {
            writeln!(out, "---@return {}", result_types.join(", ")).unwrap();
        }
        let params = binding
            .function
            .params
            .iter()
            .map(|(name, _)| param_name(name))
            .collect::<Vec<_>>();
        writeln!(
            out,
            "function M.{}({})",
            binding.lua_name,
            params.join(", ")
        )
        .unwrap();
        if binding.function.results.is_empty() {
            writeln!(
                out,
                "    component:call({:?}{})",
                binding.function.path,
                call_args(&params)
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "    return component:call({:?}{})",
                binding.function.path,
                call_args(&params)
            )
            .unwrap();
        }
        writeln!(out, "end\n").unwrap();
    }
    out.push_str("return M\n");
    out
}

struct FunctionBinding<'a> {
    function: &'a Function,
    lua_name: String,
}

fn function_bindings(functions: &[Function]) -> Vec<FunctionBinding<'_>> {
    let mut leaf_counts = BTreeMap::<String, usize>::new();
    for function in functions {
        *leaf_counts
            .entry(function_leaf(&function.path))
            .or_default() += 1;
    }

    let mut used = BTreeSet::new();
    functions
        .iter()
        .map(|function| {
            let leaf = function_leaf(&function.path);
            let preferred = if leaf_counts[&leaf] == 1 {
                lua_identifier(&leaf)
            } else {
                lua_identifier(&function.path)
            };
            let lua_name = unique_identifier(preferred, &mut used);
            FunctionBinding { function, lua_name }
        })
        .collect()
}

fn function_leaf(path: &str) -> String {
    path.rsplit('#').next().unwrap_or(path).to_string()
}

fn unique_identifier(preferred: String, used: &mut BTreeSet<String>) -> String {
    if used.insert(preferred.clone()) {
        return preferred;
    }
    for suffix in 2.. {
        let candidate = format!("{preferred}_{suffix}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
    }
    unreachable!()
}

fn call_args(params: &[String]) -> String {
    if params.is_empty() {
        String::new()
    } else {
        format!(", {}", params.join(", "))
    }
}

fn lua_identifier(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.as_bytes()[0].is_ascii_digit() {
        out.insert(0, '_');
    }
    if is_lua_keyword(&out) {
        out.push('_');
    }
    out
}

fn param_name(name: &str) -> String {
    lua_identifier(name)
}

fn is_lua_keyword(value: &str) -> bool {
    matches!(
        value,
        "and"
            | "break"
            | "do"
            | "else"
            | "elseif"
            | "end"
            | "false"
            | "for"
            | "function"
            | "goto"
            | "if"
            | "in"
            | "local"
            | "nil"
            | "not"
            | "or"
            | "repeat"
            | "return"
            | "then"
            | "true"
            | "until"
            | "while"
    )
}

fn pascal_case(value: &str) -> String {
    let mut out = String::new();
    let mut uppercase = true;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            if uppercase {
                out.push(ch.to_ascii_uppercase());
                uppercase = false;
            } else {
                out.push(ch);
            }
        } else {
            uppercase = true;
        }
    }
    if out.is_empty() || out.as_bytes()[0].is_ascii_digit() {
        out.insert(0, 'T');
    }
    out
}

fn annotated_type(
    ty: &ValueType,
    preferred_alias: String,
    aliases: &mut Vec<(String, String)>,
    used: &mut BTreeSet<String>,
) -> String {
    if !is_structural(ty) {
        return lua_type(ty);
    }
    let alias = unique_identifier(preferred_alias, used);
    aliases.push((alias.clone(), lua_type(ty)));
    alias
}

fn is_structural(ty: &ValueType) -> bool {
    match ty {
        ValueType::List(inner) => !matches!(inner.as_ref(), ValueType::U8),
        ValueType::Record(_)
        | ValueType::Tuple(_)
        | ValueType::Variant(_)
        | ValueType::Enum(_)
        | ValueType::Result { .. }
        | ValueType::Flags(_) => true,
        ValueType::Option(_) => true,
        _ => false,
    }
}

fn lua_type(ty: &ValueType) -> String {
    match ty {
        ValueType::Bool => "boolean".into(),
        ValueType::S8
        | ValueType::U8
        | ValueType::S16
        | ValueType::U16
        | ValueType::S32
        | ValueType::U32
        | ValueType::S64
        | ValueType::U64 => "integer".into(),
        ValueType::Float32 | ValueType::Float64 => "number".into(),
        ValueType::Char | ValueType::String => "string".into(),
        ValueType::List(inner) if matches!(inner.as_ref(), ValueType::U8) => "string".into(),
        ValueType::List(inner) => format!("({})[]", lua_type(inner)),
        ValueType::Record(fields) => format!(
            "{{ {} }}",
            fields
                .iter()
                .map(|(name, ty)| format!("{}: {}", lua_field(name), lua_type(ty)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        ValueType::Tuple(types) => format!(
            "{{ {} }}",
            types
                .iter()
                .enumerate()
                .map(|(index, ty)| format!("[{}]: {}", index + 1, lua_type(ty)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        ValueType::Variant(cases) => cases
            .iter()
            .map(|(name, ty)| match ty {
                Some(ty) => format!("{{ tag: {:?}, value: {} }}", name, lua_type(ty)),
                None => format!("{{ tag: {:?} }}", name),
            })
            .collect::<Vec<_>>()
            .join("|"),
        ValueType::Enum(cases) => string_union(cases),
        ValueType::Option(inner) => format!(
            "{{ tag: \"none\" }}|{{ tag: \"some\", value: {} }}",
            lua_type(inner)
        ),
        ValueType::Result { ok, err } => format!(
            "{}|{}",
            result_branch("ok", ok.as_deref()),
            result_branch("err", err.as_deref())
        ),
        ValueType::Flags(flags) => format!("({})[]", string_union(flags)),
        ValueType::Unsupported(_) => "any".into(),
    }
}

fn result_branch(name: &str, ty: Option<&ValueType>) -> String {
    match ty {
        Some(ty) => format!("{{ {name}: {} }}", lua_type(ty)),
        None => format!("{{ {name}: true }}"),
    }
}

fn string_union(values: &[String]) -> String {
    if values.is_empty() {
        return "string".into();
    }
    values
        .iter()
        .map(|value| format!("{value:?}"))
        .collect::<Vec<_>>()
        .join("|")
}

fn lua_field(name: &str) -> String {
    let identifier = lua_identifier(name);
    if identifier == name && !is_lua_keyword(name) {
        identifier
    } else {
        format!("[{name:?}]")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_callable_lua_wrapper() {
        let lua = generate_lua(
            "math",
            &[Function {
                path: "test:math/api#add".into(),
                params: vec![("a".into(), ValueType::S32), ("b".into(), ValueType::S32)],
                results: vec![ValueType::S32],
            }],
        );
        assert!(lua.contains("rpp.component.load(\"math\")"), "{lua}");
        assert!(lua.contains("function M.add(a, b)"), "{lua}");
        assert!(lua.contains("---@param a integer"), "{lua}");
        assert!(lua.contains("---@return integer"), "{lua}");
        assert!(
            lua.contains("component:call(\"test:math/api#add\", a, b)"),
            "{lua}"
        );
    }

    #[test]
    fn generates_structural_aliases_for_records_lists_variants_and_results() {
        let output_file = ValueType::Record(vec![
            ("path".into(), ValueType::String),
            ("contents".into(), ValueType::List(Box::new(ValueType::U8))),
        ]);
        let lua = generate_lua(
            "window-compiler",
            &[Function {
                path: "compile".into(),
                params: vec![(
                    "files".into(),
                    ValueType::List(Box::new(output_file.clone())),
                )],
                results: vec![ValueType::Result {
                    ok: Some(Box::new(ValueType::Variant(vec![
                        ("empty".into(), None),
                        ("files".into(), Some(ValueType::List(Box::new(output_file)))),
                    ]))),
                    err: Some(Box::new(ValueType::String)),
                }],
            }],
        );

        assert!(
            lua.contains(
                "---@alias WindowCompilerCompileFiles ({ path: string, contents: string })[]"
            ),
            "{lua}"
        );
        assert!(
            lua.contains("---@alias WindowCompilerCompileResult"),
            "{lua}"
        );
        assert!(lua.contains("{ tag: \"empty\" }"), "{lua}");
        assert!(
            lua.contains("{ tag: \"files\", value: ({ path: string, contents: string })[] }"),
            "{lua}"
        );
        assert!(
            lua.contains("---@param files WindowCompilerCompileFiles"),
            "{lua}"
        );
        assert!(
            lua.contains("---@return WindowCompilerCompileResult"),
            "{lua}"
        );
    }

    #[test]
    fn annotates_tagged_options_inside_aggregates() {
        let option = ValueType::Option(Box::new(ValueType::Bool));
        assert_eq!(
            lua_type(&option),
            r#"{ tag: "none" }|{ tag: "some", value: boolean }"#
        );
        let nested = ValueType::Option(Box::new(option.clone()));
        assert_eq!(
            lua_type(&nested),
            r#"{ tag: "none" }|{ tag: "some", value: { tag: "none" }|{ tag: "some", value: boolean } }"#
        );
        assert_eq!(
            lua_type(&ValueType::Result {
                ok: Some(Box::new(option.clone())),
                err: None
            }),
            r#"{ ok: { tag: "none" }|{ tag: "some", value: boolean } }|{ err: true }"#
        );
        assert_eq!(
            lua_type(&ValueType::List(Box::new(option))),
            r#"({ tag: "none" }|{ tag: "some", value: boolean })[]"#
        );
    }

    #[test]
    fn disambiguates_duplicate_interface_function_names() {
        let lua = generate_lua(
            "multi",
            &[
                Function {
                    path: "example:first/api#run".into(),
                    params: Vec::new(),
                    results: Vec::new(),
                },
                Function {
                    path: "example:second/api#run".into(),
                    params: Vec::new(),
                    results: Vec::new(),
                },
            ],
        );

        assert!(lua.contains("function M.example_first_api_run()"), "{lua}");
        assert!(lua.contains("function M.example_second_api_run()"), "{lua}");
    }

    #[test]
    fn sanitizes_all_lua_identifiers_and_record_fields() {
        let lua = generate_lua(
            "keywords",
            &[Function {
                path: "1-call".into(),
                params: vec![(
                    "repeat".into(),
                    ValueType::Record(vec![
                        ("end".into(), ValueType::Bool),
                        ("hyphen-name".into(), ValueType::String),
                    ]),
                )],
                results: Vec::new(),
            }],
        );

        assert!(lua.contains("function M._1_call(repeat_)"), "{lua}");
        assert!(lua.contains("[\"end\"]: boolean"), "{lua}");
        assert!(lua.contains("[\"hyphen-name\"]: string"), "{lua}");
    }
}
