[package]
name = "rpp"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
once_cell = "1.21.3"
rayon = "1.10.0"
ignore = "0.4.25"
tracing = { version = "0.1", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
jsonc-parser = { version = "0.27.0", features = ["serde"] }
mlua = { version = "0.11.3", features = ["vendored", "luajit52", "serde"] }
thiserror = "2.0.17"
include_directory = "0.1.1"
regex = "1.12.2"
toml = "0.9.8"

[features]
default = []
tracing = ["dep:tracing"]
